include:
  - project: cs/gitlabci-templates
    file: /build-image-using-kaniko.yml

stages:
  - lint
  - test
  - deploy

variables:
  KUBERNETES_MEMORY_LIMIT: 8Gi
  KUBERNETES_MEMORY_REQUEST: 8Gi


lint_black:
  image: python:3.10.12
  stage: lint
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false && poetry install
    - black --version
  script:
    - black --check .

lint_pylint:
  image: python:3.10.12
  stage: lint
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false && poetry install
  script:
    - pylint api

unit_tests:
  image: python:3.10.12
  stage: test
  before_script:
    - pip install poetry
    - poetry config virtualenvs.create false && poetry install
  script:
    - pytest

build-and-deploy-api-image-in-registry:
  stage: deploy
  extends: .build-image-using-kaniko
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: on_success
      variables:
        CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/thumbnail-generation-api-dev
    - if: $CI_COMMIT_TAG
      when: on_success
      variables:
        CI_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/thumbnail-generation-api-production
  variables:
    CI_COMMIT_SHORT_SHA: $CI_COMMIT_SHORT_SHA
    REGISTRY_IMAGE_TAG: $CI_COMMIT_SHORT_SHA-$(date +%s)
