
[tool.pylint.FORMAT]
max-line-length=120
good-names=["version_template"]
disable =["R0903"]

[tool.pylint.MASTER]
extension-pkg-whitelist=["pydantic"]

[tool.pylint.messages_control]
disable = ["unnecessary-pass"]

[tool.black]
line-length=120